import { prisma } from "@/lib/prisma";
import { NextResponse } from "next/server";

const careersData = [
  {
    name: "Accountant (CA/PA)",
    industry: "Finance & Accounting",
    description: "Manages financial records, taxes, and audits",
    whatItIs: "An accountant is a financial professional responsible for managing, recording, and analyzing financial information for individuals, businesses, and organizations.",
    whatTheyDo: "Maintains accurate records, prepares tax returns, generates financial statements, conducts audits, analyzes costs, manages payroll, and helps develop budgets.",
    skillsNeeded: ["Numerical accuracy", "Integrity", "Analytical thinking", "Excel proficiency", "IFRS knowledge"],
    certifications: ["CA(SA)", "ACCA", "IRBA"],
    tertiaryInstitutions: ["University of Cape Town (UCT)", "University of the Witwatersrand (Wits)", "University of Pretoria (UP)", "Stellenbosch University", "UNISA"],
    image: "https://picsum.photos/400/300?random=1",
  },
  {
    name: "Actuary",
    industry: "Finance & Insurance",
    description: "Uses math and statistics to assess risk",
    whatItIs: "An actuary is a financial professional who uses mathematics, statistics, and financial theories to assess and manage financial risks.",
    whatTheyDo: "Analyzes financial risks, creates mathematical models, develops pricing strategies, values liabilities, conducts stress testing, and provides expert advice.",
    skillsNeeded: ["Advanced mathematics", "Statistics", "Problem-solving", "Financial modeling", "Python/R"],
    certifications: ["FAI", "ASA", "EA"],
    tertiaryInstitutions: ["University of the Witwatersrand (Wits)", "University of Cape Town (UCT)", "University of Pretoria (UP)", "Stellenbosch University", "North-West University (NWU)"],
    image: "https://picsum.photos/400/300?random=2",
  },
  {
    name: "Advocate",
    industry: "Legal Services",
    description: "Legal specialist who represents clients in court",
    whatItIs: "An advocate is a legal specialist in South Africa who provides legal representation in court. They typically work independently or in chambers.",
    whatTheyDo: "Represents clients in legal proceedings, handles litigation, conducts legal research, writes opinions, negotiates settlements, and prepares cases for trial.",
    skillsNeeded: ["Public speaking", "Litigation knowledge", "Legal research", "Critical thinking", "Negotiation"],
    certifications: ["LLB", "Admitted to the Bar"],
    tertiaryInstitutions: ["University of Cape Town (UCT)", "Rhodes University", "University of Johannesburg (UJ)", "University of KwaZulu-Natal (UKZN)", "University of Pretoria (UP)"],
    image: "https://picsum.photos/400/300?random=3",
  },
  {
    name: "Aerospace Engineer",
    industry: "Aerospace & Defense",
    description: "Designs and develops aircraft and spacecraft systems",
    whatItIs: "An aerospace engineer designs, develops, tests, and manufactures aircraft, spacecraft, and related systems using principles of aerodynamics and physics.",
    whatTheyDo: "Designs aircraft components, conducts aerodynamic analysis, performs testing, selects materials, ensures safety standards, and optimizes performance.",
    skillsNeeded: ["Physics", "Calculus", "CAD software", "Aerodynamics", "Problem-solving"],
    certifications: ["Professional Engineer (PE)", "CFTE"],
    tertiaryInstitutions: ["University of the Witwatersrand (Wits)", "University of Pretoria (UP)"],
    image: "https://picsum.photos/400/300?random=4",
  },
  {
    name: "Agricultural Scientist",
    industry: "Agriculture & Environment",
    description: "Studies soil, crops, and livestock for productivity",
    whatItIs: "An agricultural scientist conducts research and applies scientific principles to improve farming practices, crop yields, and livestock productivity.",
    whatTheyDo: "Conducts research, analyzes soil, develops crop varieties, manages diseases, controls pests, improves livestock productivity, and publishes findings.",
    skillsNeeded: ["Research methodology", "Biology", "Environmental awareness", "Statistical analysis", "Data analysis"],
    certifications: ["Certified Agronomist"],
    tertiaryInstitutions: ["University of Pretoria (UP)", "Stellenbosch University", "University of KwaZulu-Natal (UKZN)", "North-West University (NWU)", "University of Fort Hare"],
    image: "https://picsum.photos/400/300?random=5",
  },
  {
    name: "Air Traffic Controller",
    industry: "Aviation",
    description: "Coordinates aircraft movement for safe travel",
    whatItIs: "An air traffic controller manages aircraft movement on the ground and in the air to ensure safe distances and efficient flight operations.",
    whatTheyDo: "Coordinates aircraft movements, ensures safe separation, communicates with pilots, plans routes, handles emergencies, and monitors weather.",
    skillsNeeded: ["Spatial awareness", "Decision-making", "Calm under pressure", "Communication", "Quick thinking"],
    certifications: ["Air Traffic Control License"],
    tertiaryInstitutions: ["ATNS Aviation Training Academy", "Wits University", "University of Johannesburg (UJ)"],
    image: "https://picsum.photos/400/300?random=6",
  },
  {
    name: "Anaesthetist",
    industry: "Healthcare",
    description: "Medical doctor specializing in anesthesia administration",
    whatItIs: "An anaesthetist is a medical doctor specializing in administering anesthesia and managing patient vitals during surgical procedures.",
    whatTheyDo: "Administers anesthesia, monitors vital signs, manages pain, controls airway, assesses patients, provides post-operative care, and handles emergencies.",
    skillsNeeded: ["Medical knowledge", "Vigilance", "Critical care", "Attention to detail", "Calm under pressure"],
    certifications: ["MB ChB", "Anaesthesia specialization"],
    tertiaryInstitutions: ["University of Cape Town (UCT)", "University of the Witwatersrand (Wits)", "University of Pretoria (UP)", "Stellenbosch University", "University of KwaZulu-Natal (UKZN)"],
    image: "https://picsum.photos/400/300?random=7",
  },
  {
    name: "Architect",
    industry: "Construction & Design",
    description: "Plans and designs buildings and structures",
    whatItIs: "An architect is a professional who designs and plans buildings and structures, balancing aesthetics, functionality, safety, and sustainability.",
    whatTheyDo: "Designs buildings, creates architectural drawings, analyzes sites, ensures compliance, estimates costs, manages projects, and incorporates sustainability.",
    skillsNeeded: ["Creativity", "Spatial design", "Technical drawing", "CAD software", "Problem-solving"],
    certifications: ["B.Arch(Prof)"],
    tertiaryInstitutions: ["University of Cape Town (UCT)", "University of the Witwatersrand (Wits)", "University of Pretoria (UP)", "University of KwaZulu-Natal (UKZN)", "Tshwane University of Technology (TUT)"],
    image: "https://picsum.photos/400/300?random=8",
  },
  {
    name: "Attorney",
    industry: "Legal Services",
    description: "Provides legal advice and manages legal matters",
    whatItIs: "An attorney is a legal professional who provides direct legal advice to clients and manages legal matters including contracts and litigation.",
    whatTheyDo: "Provides legal advice, drafts contracts, negotiates agreements, manages litigation, builds client relationships, conducts research, and ensures compliance.",
    skillsNeeded: ["Negotiation", "Legal drafting", "Empathy", "Legal knowledge", "Critical thinking"],
    certifications: ["LLB", "Admission to practice"],
    tertiaryInstitutions: ["University of Cape Town (UCT)", "University of the Witwatersrand (Wits)", "University of Pretoria (UP)", "Stellenbosch University", "University of Johannesburg (UJ)"],
    image: "https://picsum.photos/400/300?random=9",
  },
  {
    name: "Audiologist",
    industry: "Healthcare",
    description: "Diagnoses and treats hearing and balance disorders",
    whatItIs: "An audiologist is a healthcare professional who specializes in diagnosing and treating hearing and balance disorders.",
    whatTheyDo: "Conducts hearing tests, diagnoses disorders, fits hearing aids, provides rehabilitation, counsels patients, and educates about hearing health.",
    skillsNeeded: ["Communication", "Technical proficiency", "Patience", "Patient education", "Attention to detail"],
    certifications: ["B.Sc(Hons) Audiology"],
    tertiaryInstitutions: ["University of the Witwatersrand (Wits)", "University of Cape Town (UCT)", "University of Pretoria (UP)", "University of KwaZulu-Natal (UKZN)"],
    image: "https://picsum.photos/400/300?random=10",
  },
  {
    name: "Auditor (Internal/External)",
    industry: "Finance & Accounting",
    description: "Examines financial statements and internal controls",
    whatItIs: "An auditor is a professional who examines financial statements, internal controls, and procedures to ensure accuracy and prevent fraud.",
    whatTheyDo: "Examines financial records, plans audits, tests controls, reviews compliance, assesses risks, detects fraud, and provides recommendations.",
    skillsNeeded: ["Skepticism", "Ethics", "Detail-oriented", "IT literacy", "Financial analysis"],
    certifications: ["APA", "CA(SA)", "IRBA"],
    tertiaryInstitutions: ["University of Cape Town (UCT)", "University of Pretoria (UP)", "University of the Witwatersrand (Wits)"],
    image: "https://picsum.photos/400/300?random=11",
  },
  {
    name: "Business Analyst",
    industry: "Technology & Business",
    description: "Bridges business needs and technical solutions",
    whatItIs: "A business analyst is a professional who analyzes business processes and recommends improvements or new systems to increase efficiency.",
    whatTheyDo: "Gathers requirements, analyzes processes, identifies gaps, designs solutions, documents findings, conducts testing, and supports implementation.",
    skillsNeeded: ["Data analysis", "Business process modeling", "SQL", "JIRA", "Communication"],
    certifications: ["CBAP", "IIBA certification"],
    tertiaryInstitutions: ["University of Johannesburg (UJ)", "Wits University", "University of Cape Town (UCT)"],
    image: "https://picsum.photos/400/300?random=12",
  },
  {
    name: "Civil Engineer",
    industry: "Engineering & Construction",
    description: "Designs, builds, and maintains infrastructure",
    whatItIs: "A civil engineer designs, builds, and maintains infrastructure projects including roads, bridges, buildings, and water systems.",
    whatTheyDo: "Designs projects, surveys sites, plans budgets, leads teams, ensures quality standards, complies with regulations, analyzes structures, and monitors progress.",
    skillsNeeded: ["Physics", "Calculus", "AutoCAD", "Attention to detail", "Leadership"],
    certifications: ["Professional Engineer (PE)", "B.Sc(Eng)"],
    tertiaryInstitutions: ["University of Cape Town (UCT)", "University of the Witwatersrand (Wits)", "University of Pretoria (UP)", "Stellenbosch University"],
    image: "https://picsum.photos/400/300?random=13",
  },
  {
    name: "Data Scientist",
    industry: "Technology & Data",
    description: "Analyzes data to drive business decisions",
    whatItIs: "A data scientist is a professional who extracts insights from data using statistical analysis, machine learning, and programming.",
    whatTheyDo: "Collects data, cleans data, performs statistical analysis, develops models, creates visualizations, provides insights, and deploys solutions.",
    skillsNeeded: ["Python", "Statistics", "SQL", "Machine learning", "Data visualization"],
    certifications: ["Google Data Analytics Certificate", "IBM Data Science Professional"],
    tertiaryInstitutions: ["University of the Witwatersrand (Wits)", "University of Cape Town (UCT)", "University of Johannesburg (UJ)"],
    image: "https://picsum.photos/400/300?random=14",
  },
  {
    name: "Electrical Engineer",
    industry: "Engineering",
    description: "Designs and maintains electrical equipment and systems",
    whatItIs: "An electrical engineer designs, develops, and maintains electrical equipment and systems including power systems and electronics.",
    whatTheyDo: "Designs systems, plans installations, tests components, troubleshoots faults, performs maintenance, ensures compliance, and supervises teams.",
    skillsNeeded: ["Circuit analysis", "CAD software", "Electrical codes", "Power systems", "Problem-solving"],
    certifications: ["Professional Engineer (PE)", "B.Sc(Eng)"],
    tertiaryInstitutions: ["University of Cape Town (UCT)", "University of the Witwatersrand (Wits)", "University of Pretoria (UP)", "Stellenbosch University"],
    image: "https://picsum.photos/400/300?random=15",
  },
  {
    name: "Financial Advisor",
    industry: "Finance",
    description: "Provides personalized financial guidance to clients",
    whatItIs: "A financial advisor is a professional who provides personalized financial guidance including investments, retirement, and wealth management.",
    whatTheyDo: "Develops financial plans, analyzes investments, assesses risks, plans for retirement, recommends insurance, plans taxes, and manages assets.",
    skillsNeeded: ["Financial analysis", "Investment analysis", "Tax knowledge", "Communication", "Trustworthiness"],
    certifications: ["CFP", "CFA", "FPISA certification"],
    tertiaryInstitutions: ["University of Cape Town (UCT)", "University of Johannesburg (UJ)", "Wits University", "Stellenbosch University"],
    image: "https://picsum.photos/400/300?random=16",
  },
  {
    name: "Graphic Designer",
    industry: "Design & Creative",
    description: "Creates visual content for various media",
    whatItIs: "A graphic designer is a creative professional who creates visual content including logos, advertisements, and websites.",
    whatTheyDo: "Develops brand identity, creates marketing materials, designs websites, creates packaging, produces social media content, and researches trends.",
    skillsNeeded: ["Adobe Creative Suite", "Design principles", "Typography", "Color theory", "Creativity"],
    certifications: ["Adobe Certified Associate", "B.Tech Graphic Design"],
    tertiaryInstitutions: ["University of Johannesburg (UJ)", "Vega School", "IIE Varsity College", "Durban University of Technology (DUT)"],
    image: "https://picsum.photos/400/300?random=17",
  },
  {
    name: "Human Resources Manager",
    industry: "Human Resources",
    description: "Oversees recruitment, training, and employee management",
    whatItIs: "An HR manager oversees recruitment, training, development, and management of employees while ensuring compliance with labor laws.",
    whatTheyDo: "Recruits employees, conducts onboarding, designs training, manages performance, handles relations, develops policies, ensures compliance, and creates culture.",
    skillsNeeded: ["Communication", "Conflict resolution", "Empathy", "Leadership", "Knowledge of labor laws"],
    certifications: ["SABPP certification", "B.Com HR Management"],
    tertiaryInstitutions: ["University of Johannesburg (UJ)", "Wits University", "University of Cape Town (UCT)", "University of Pretoria (UP)"],
    image: "https://picsum.photos/400/300?random=18",
  },
  {
    name: "IT Systems Administrator",
    industry: "Technology",
    description: "Manages computer systems, networks, and servers",
    whatItIs: "An IT systems administrator manages and maintains an organization's computer systems, networks, and servers.",
    whatTheyDo: "Maintains systems, provides user support, installs software, manages security, manages backups, monitors networks, manages licenses, and troubleshoots.",
    skillsNeeded: ["Windows/Linux administration", "Networking", "Active Directory", "Virtualization", "Security protocols"],
    certifications: ["CompTIA A+", "Network+", "Security+"],
    tertiaryInstitutions: ["University of Johannesburg (UJ)", "Wits University", "Durban University of Technology (DUT)"],
    image: "https://picsum.photos/400/300?random=19",
  },
  {
    name: "Journalist",
    industry: "Media & Communication",
    description: "Researches and reports news to the public",
    whatItIs: "A journalist is a professional who researches, investigates, and reports news and information across various media platforms.",
    whatTheyDo: "Researches stories, conducts interviews, writes articles, edits content, verifies facts, produces multimedia, meets deadlines, and engages audience.",
    skillsNeeded: ["Writing", "Research", "Critical thinking", "Multimedia editing", "Time management"],
    certifications: ["B.Com Journalism", "B.A(Hons) Journalism"],
    tertiaryInstitutions: ["University of Johannesburg (UJ)", "University of the Witwatersrand (Wits)", "Rhodes University", "University of Cape Town (UCT)"],
    image: "https://picsum.photos/400/300?random=20",
  },
  {
    name: "Kinesiotherapist",
    industry: "Healthcare",
    description: "Uses therapeutic exercise to improve physical function",
    whatItIs: "A kinesiotherapist is a healthcare professional who uses therapeutic exercise and movement to improve physical function and health.",
    whatTheyDo: "Assesses patients, develops programs, teaches exercises, monitors progress, manages pain, provides rehabilitation, educates patients, and documents care.",
    skillsNeeded: ["Anatomy knowledge", "Exercise science", "Therapeutic techniques", "Assessment skills", "Empathy"],
    certifications: ["B.Sc(Hons) Physiotherapy"],
    tertiaryInstitutions: ["University of the Witwatersrand (Wits)", "University of Cape Town (UCT)", "Stellenbosch University", "University of Johannesburg (UJ)"],
    image: "https://picsum.photos/400/300?random=21",
  },
  {
    name: "Lawyer",
    industry: "Legal Services",
    description: "Provides legal advice and representation",
    whatItIs: "A lawyer is a legal professional who provides legal advice and representation to clients in various legal matters.",
    whatTheyDo: "Provides legal advice, drafts documents, represents in court, conducts research, negotiates agreements, ensures compliance, and advocates for clients.",
    skillsNeeded: ["Legal knowledge", "Negotiation", "Analytical thinking", "Communication", "Ethics"],
    certifications: ["LLB", "Admitted to practice"],
    tertiaryInstitutions: ["University of Cape Town (UCT)", "University of the Witwatersrand (Wits)", "University of Pretoria (UP)", "Stellenbosch University"],
    image: "https://picsum.photos/400/300?random=22",
  },
  {
    name: "Marketing Manager",
    industry: "Marketing & Business",
    description: "Develops and executes marketing strategies",
    whatItIs: "A marketing manager develops and executes marketing strategies to promote products and increase brand awareness.",
    whatTheyDo: "Develops strategies, manages campaigns, researches markets, manages budgets, oversees branding, manages digital marketing, and analyzes performance.",
    skillsNeeded: ["Strategic thinking", "Creativity", "Communication", "Analytics", "Leadership"],
    certifications: ["Google Digital Marketing Certificate", "HubSpot Marketing Certification"],
    tertiaryInstitutions: ["University of Johannesburg (UJ)", "University of Cape Town (UCT)", "Wits University", "Stellenbosch University"],
    image: "https://picsum.photos/400/300?random=23",
  },
  {
    name: "Nurse",
    industry: "Healthcare",
    description: "Provides care to patients in healthcare settings",
    whatItIs: "A nurse is a healthcare professional who provides care to patients in hospitals, clinics, and other healthcare settings.",
    whatTheyDo: "Provides patient care, monitors vitals, administers medications, manages wounds, assesses patients, educates patients, maintains records, and collaborates.",
    skillsNeeded: ["Compassion", "Communication", "Patience", "Attention to detail", "Physical capability"],
    certifications: ["B.Sc(Hons) Nursing", "SANC registration"],
    tertiaryInstitutions: ["University of the Witwatersrand (Wits)", "University of Cape Town (UCT)", "University of Johannesburg (UJ)", "Durban University of Technology (DUT)"],
    image: "https://picsum.photos/400/300?random=24",
  },
  {
    name: "Operations Manager",
    industry: "Business & Management",
    description: "Oversees day-to-day operational activities",
    whatItIs: "An operations manager oversees the day-to-day operations of a company to ensure processes run efficiently.",
    whatTheyDo: "Manages processes, ensures quality, controls costs, schedules resources, manages vendors, tracks metrics, addresses issues, and leads teams.",
    skillsNeeded: ["Leadership", "Problem-solving", "Process improvement", "Communication", "Decision-making"],
    certifications: ["B.Com Operations Management", "APICS certification"],
    tertiaryInstitutions: ["University of Johannesburg (UJ)", "Wits University", "University of Cape Town (UCT)"],
    image: "https://picsum.photos/400/300?random=25",
  },
  {
    name: "Project Manager",
    industry: "Business & Management",
    description: "Plans, executes, and oversees projects",
    whatItIs: "A project manager plans, executes, and oversees projects to ensure they are completed on time and within budget.",
    whatTheyDo: "Plans projects, allocates resources, manages budgets, manages risks, communicates with stakeholders, leads teams, ensures quality, and manages changes.",
    skillsNeeded: ["Leadership", "Communication", "Planning", "Problem-solving", "Time management"],
    certifications: ["PMP", "CAPM", "Prince2"],
    tertiaryInstitutions: ["University of Johannesburg (UJ)", "Wits University", "University of Cape Town (UCT)"],
    image: "https://picsum.photos/400/300?random=26",
  },
  {
    name: "Quality Assurance Engineer",
    industry: "Technology",
    description: "Ensures products meet quality standards",
    whatItIs: "A quality assurance engineer develops and implements processes to ensure products or services meet quality standards.",
    whatTheyDo: "Develops test plans, creates test cases, performs testing, documents defects, tracks issues, performs analysis, reports results, and recommends improvements.",
    skillsNeeded: ["Attention to detail", "Problem-solving", "Testing tools", "SQL", "Communication"],
    certifications: ["ISTQB certification", "B.Tech IT"],
    tertiaryInstitutions: ["University of Johannesburg (UJ)", "Wits University", "Durban University of Technology (DUT)"],
    image: "https://picsum.photos/400/300?random=27",
  },
  {
    name: "Real Estate Agent",
    industry: "Real Estate & Property",
    description: "Facilitates buying, selling, and renting of properties",
    whatItIs: "A real estate agent is a professional who facilitates the buying, selling, and renting of properties.",
    whatTheyDo: "Lists properties, conducts showings, analyzes markets, negotiates offers, prepares documents, markets properties, communicates with clients, and builds relationships.",
    skillsNeeded: ["Negotiation", "Communication", "Customer service", "Market knowledge", "Detail-oriented"],
    certifications: ["EAAB licensing", "Real Estate certification"],
    tertiaryInstitutions: ["University of Johannesburg (UJ)", "Wits University", "University of Cape Town (UCT)"],
    image: "https://picsum.photos/400/300?random=28",
  },
  {
    name: "Software Developer",
    industry: "Technology",
    description: "Builds and maintains software applications",
    whatItIs: "A software developer designs, builds, and maintains software applications using programming languages and development tools.",
    whatTheyDo: "Writes code, designs systems, fixes bugs, performs testing, documents code, collaborates with teams, solves problems, and optimizes performance.",
    skillsNeeded: ["Programming languages", "Problem-solving", "Version control", "Database design", "Communication"],
    certifications: ["AWS Certified Developer", "B.Sc Computer Science"],
    tertiaryInstitutions: ["University of Cape Town (UCT)", "University of the Witwatersrand (Wits)", "Stellenbosch University", "University of Johannesburg (UJ)"],
    image: "https://picsum.photos/400/300?random=29",
  },
  {
    name: "Teacher",
    industry: "Education",
    description: "Imparts knowledge and skills to students",
    whatItIs: "A teacher is an educator who imparts knowledge and skills to students in educational settings.",
    whatTheyDo: "Develops lesson plans, delivers instruction, assesses learning, provides support, grades assignments, communicates with parents, and participates in professional development.",
    skillsNeeded: ["Communication", "Patience", "Classroom management", "Subject expertise", "Enthusiasm"],
    certifications: ["B.Ed", "PGCE"],
    tertiaryInstitutions: ["University of Cape Town (UCT)", "University of the Witwatersrand (Wits)", "Stellenbosch University", "University of Johannesburg (UJ)"],
    image: "https://picsum.photos/400/300?random=30",
  },
  {
    name: "Urban Planner",
    industry: "Urban Planning & Development",
    description: "Develops plans for city and regional growth",
    whatItIs: "An urban planner develops and implements plans for city and regional growth considering sustainability and community needs.",
    whatTheyDo: "Analyzes sites, develops master plans, recommends zoning, plans transportation, assesses environment, engages community, establishes standards, and implements plans.",
    skillsNeeded: ["Strategic thinking", "GIS software", "Communication", "Problem-solving", "Creativity"],
    certifications: ["B.Sc(Hons) Urban Design", "Master's in Urban Planning"],
    tertiaryInstitutions: ["University of Cape Town (UCT)", "University of the Witwatersrand (Wits)", "Stellenbosch University"],
    image: "https://picsum.photos/400/300?random=31",
  },
  {
    name: "Veterinarian",
    industry: "Animal Health & Veterinary",
    description: "Diagnoses and treats diseases in animals",
    whatItIs: "A veterinarian is a medical professional who diagnoses and treats diseases and injuries in animals.",
    whatTheyDo: "Diagnoses conditions, provides medical treatment, performs surgery, administers vaccinations, provides preventive care, maintains records, and advises clients.",
    skillsNeeded: ["Anatomy knowledge", "Medical skills", "Communication", "Compassion for animals", "Surgical skills"],
    certifications: ["B.Sc(Hons) Veterinary Science"],
    tertiaryInstitutions: ["University of Pretoria (UP)"],
    image: "https://picsum.photos/400/300?random=32",
  },
  {
    name: "Web Developer",
    industry: "Technology",
    description: "Designs and develops websites and web applications",
    whatItIs: "A web developer designs and develops websites and web applications using programming languages and web technologies.",
    whatTheyDo: "Develops websites, writes code, integrates databases, develops APIs, implements UI designs, optimizes performance, conducts testing, and maintains sites.",
    skillsNeeded: ["HTML/CSS", "JavaScript", "Backend languages", "Database management", "Problem-solving"],
    certifications: ["B.Sc Computer Science", "Web Development bootcamp"],
    tertiaryInstitutions: ["University of Cape Town (UCT)", "University of Johannesburg (UJ)", "IIE Varsity College"],
    image: "https://picsum.photos/400/300?random=33",
  },
  {
    name: "X-Ray Technician",
    industry: "Healthcare",
    description: "Operates imaging equipment for medical diagnosis",
    whatItIs: "An X-ray technician operates imaging equipment to produce diagnostic radiographic images for medical diagnosis.",
    whatTheyDo: "Positions patients, operates equipment, ensures image quality, implements safety protocols, maintains records, processes images, and follows procedures.",
    skillsNeeded: ["Technical proficiency", "Anatomy knowledge", "Safety awareness", "Communication", "Attention to detail"],
    certifications: ["B.Tech Radiography"],
    tertiaryInstitutions: ["University of the Witwatersrand (Wits)", "Durban University of Technology (DUT)", "CPUT"],
    image: "https://picsum.photos/400/300?random=34",
  },
  {
    name: "Youth Counselor",
    industry: "Social Services & Mental Health",
    description: "Provides emotional support to young people",
    whatItIs: "A youth counselor provides emotional support and guidance to young people facing personal, social, or behavioral challenges.",
    whatTheyDo: "Provides counseling, assesses needs, develops plans, facilitates groups, intervenes in crises, refers to services, conducts family sessions, and advocates.",
    skillsNeeded: ["Empathy", "Active listening", "Communication", "Patience", "Problem-solving"],
    certifications: ["B.A Psychology", "Counselor certification"],
    tertiaryInstitutions: ["University of Cape Town (UCT)", "University of the Witwatersrand (Wits)", "Stellenbosch University", "University of Johannesburg (UJ)"],
    image: "https://picsum.photos/400/300?random=35",
  },
  {
    name: "Zoologist",
    industry: "Science & Environment",
    description: "Studies animals and their behavior in ecosystems",
    whatItIs: "A zoologist is a scientist who studies animals, their behavior, habitats, and ecosystems to understand and protect wildlife.",
    whatTheyDo: "Conducts research, performs field studies, analyzes data, publishes findings, develops conservation strategies, and provides education.",
    skillsNeeded: ["Biology knowledge", "Research methodology", "Data analysis", "Critical thinking", "Communication"],
    certifications: ["B.Sc(Hons) Zoology"],
    tertiaryInstitutions: ["University of Cape Town (UCT)", "University of the Witwatersrand (Wits)", "Stellenbosch University", "University of Pretoria (UP)"],
    image: "https://picsum.photos/400/300?random=36",
  },
];

export async function POST(request: Request) {
  try {
    // Clear existing careers
    await prisma.career.deleteMany({});
    console.log("Cleared existing careers");

    // Create careers
    for (const career of careersData) {
      await prisma.career.create({
        data: career,
      });
    }

    console.log(`Successfully seeded ${careersData.length} careers`);

    return NextResponse.json({
      success: true,
      message: `Successfully seeded ${careersData.length} careers`,
    });
  } catch (error) {
    console.error("Error seeding careers:", error);
    return NextResponse.json(
      { error: "Failed to seed careers" },
      { status: 500 }
    );
  }
}
